version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-test}"
    image: localstack/localstack-pro:latest
    #network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      #- SERVICES=${SERVICES-serverless,route53,sns,sqs,s3,apigateway, }
      #- DEBUG=${DEBUG-1 }
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOSTNAME=localhost
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-local }
      - LAMBDA_REMOVE_CONTAINERS=true
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PROVIDER_OVERRIDE_LAMBDA=v2
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack-config/:/etc/localstack/init/ready.d
